language: ruby

rvm:
  - 2.2

before_script:
  - gem install awesome_bot
  - gem install mdl

script:
- awesome_bot README.md --allow-dupe  # Allow duplicate links
- mdl --rules ~MD013 README.md # Ignore line length (MD013) and inline HTML (MD033) Rules
